### ISSUE TITLE
Unit warnings in docs

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#1498] opened 2020-12-30 10:04 UTC
In the following places in the docs, `scipp.neutron.load` prints these errors:
```
Workspace run log 'proton_charge' has unrecognised units: 'picoCoulombs'
Workspace run log 'gd_prtn_chrg' has unrecognised units: 'uA.hour'
```
- https://scipp.github.io/scipp-neutron/instrument-view.html
- https://scipp.github.io/scipp-neutron/groupby.html
- https://scipp.github.io/tutorials/neutron-diffraction.html

Not sure if this is an issue with Scipp of Mantid, though.

**Comment by SimonHeybrock** [comment] 2021-01-11 06:10
The issue is 2-fold:
- The units in Mantid are just strings, and there appears to be no strict schema. I have seen, e.g., cases where `' '` is used for dimensionless.
- Scipp does not support all the required units at this point.
Adding missing SI base units is the least of issues, but I am not sure how to best handle the unit scales (pice, micro, hour instead of second, ...). Unit scales have always been on the to do list, but pretty far down, but I think we will need to address it rather sooner than later (which may involve switching to a more flexibly system instead of boost.units, or not).

**Comment by SimonHeybrock** [comment] 2021-02-22 12:21
Fixed by move to llnl/units.

**Closed by SimonHeybrock** 2021-02-22 12:21 UTC
Labels: docs, neutron
