### ISSUE TITLE
Support grouping with tuple-like coordinates.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scipp#3426] opened 2024-04-17 09:52 UTC
It'll be useful if there is a `tuple[int]` dtype and we support grouping by them.

### NMX scaling
It was needed in the nmx package, for grouping the dataset by `miller indices (hkl)` for scaling.
For example,
we want to bin the data into wavelength(LAMDA) and and select the reference group for deriving scale-factor of intensity.
Then we want to group the binned data by `miller indices`.
They should be grouped by the `miller indices` of the reference bin, so that we can scale the intensity per miller indices/ per wavelength(LAMBDA).
Related to https://github.com/scipp/essnmx/pull/57

**Comment by SimonHeybrock** [comment] 2024-04-17 09:54
I'll close this as duplicate of #3046

**Closed by SimonHeybrock** 2024-04-17 09:54 UTC
Labels: enhancement
