### ISSUE TITLE
Segfault with llnl units via `convert` on one (known) platform

### ISSUE THREAD

**Issue by OwenArnold** [scipp/scipp#1829] opened 2021-04-16 13:03 UTC
* Problem observed with `scippneutron::convert`, but is acutally a problem in `scipp/units(llnl)`
* Only happens on ubuntu 64 to our knowledge. Problem not observed on osx or rhel7.
* Results from https://github.com/SimonHeybrock/units/commit/04f40061d1c7e57d2629c4bc1112dca24153a558, moving to earlier `HEAD~1` does not show issue
* We find a corrupted `precise_unit` at the point of segfault. though the cause has not been pinpointed.

**To emulate**

1. Download `units-bug.yml` [units-bug.txt](https://github.com/scipp/scipp/files/6325204/units-bug.txt)
1. `conda env create -f units-bug.yml && conda activate units-bug`
1.  Go to the scippneutron root git directory
1. `python -m pytest python/tests/test_neutron.py::test_neutron_convert`

FYI, since the special packages created to show this are made with debug symbols, it should be possible to run this all under `gdb`

**Comment by jl-wynen** [comment] 2021-04-16 13:16
Segfaults for me, too.
OS: Manjaro 21
Compiler: gcc 10.2.0

**Comment by matthew-d-jones** [comment] 2021-04-16 14:23
Segfaults for me
OS: Ubuntu 20.04
Compiler: gcc 9.3.0

**Comment by matthew-d-jones** [comment] 2021-04-16 14:32
I have also confirmed that I don't see the segfault if I set `UNITS_BASE_TYPE` to `uint32_t` when building the units library.

**Comment by SimonHeybrock** [comment] 2021-04-19 04:59
Can someone who can reproduce this try with this branch of `units`: https://github.com/SimonHeybrock/units/tree/unit-data-size-fixes.

It seems the hashing was missing half of the class, but I am not sure if that could be the cause of what you are seeing.

**Comment by matthew-d-jones** [comment] 2021-04-19 06:07
Looks like that does fix the problem.

**Comment by SimonHeybrock** [comment] 2021-04-20 04:23
I have updated our fork after the upstream changes were merged. You may need to remove the `llnl-units*`folder from your builds so `cmake` will update. Please reopen if it still crashes for you.

**Closed by SimonHeybrock** 2021-04-20 04:23 UTC
Labels: bug
