### ISSUE TITLE
test_bins_concat_masking fails

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/scipp#2926] opened 2023-01-05 08:57 UTC
```

============================================================================= FAILURES =============================================================================
_____________________________________________________________________ test_bins_concat_masking _____________________________________________________________________
[gw4] linux -- Python 3.10.8 /home/sunyoung/ESS/scipp/.tox/test/bin/python

    @settings(max_examples=100, deadline=1000)
>   @given(st.integers(min_value=1, max_value=12345),
           scst.variables(dtype=bool, ndim=st.integers(min_value=1, max_value=3)))

tests/hypothesis/bin_test.py:50: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (725, <scipp.Variable> (: 4, 2: 9, 0: 4)       bool        <no unit>  [True, True, ..., True, True]), kwargs = {}, initial_draws = 1, start = 9518.195407786
result = None, finish = 9519.379207664, internal_draw_time = 0, runtime = datetime.timedelta(seconds=1, microseconds=183800)
current_deadline = timedelta(milliseconds=1000)

    @proxies(self.test)
    def test(*args, **kwargs):
        self.__test_runtime = None
        initial_draws = len(data.draw_times)
        start = time.perf_counter()
        result = self.test(*args, **kwargs)
        finish = time.perf_counter()
        internal_draw_time = sum(data.draw_times[initial_draws:])
        runtime = datetime.timedelta(
            seconds=finish - start - internal_draw_time
        )
        self.__test_runtime = runtime
        current_deadline = self.settings.deadline
        if not is_final:
            current_deadline = (current_deadline // 4) * 5
        if runtime >= current_deadline:
>           raise DeadlineExceeded(runtime, self.settings.deadline)
E           hypothesis.errors.DeadlineExceeded: Test took 1183.80ms, which exceeds the deadline of 1000.00ms
E           Falsifying example: test_bins_concat_masking(
E               mask=<scipp.Variable> (: 4, 2: 9, 0: 4)       bool  [dimensionless]  [True, True, ..., True, True],
E               nevent=725,
E           )

.tox/test/lib/python3.10/site-packages/hypothesis/core.py:694: DeadlineExceeded
 
```

**Comment by jl-wynen** [comment] 2023-01-11 15:28
I checked what hypothesis' deadline means. It is only about the run time of the test itself. It does not include the strategy.
So the failure here is a problem with the test itself, not hypothesis or our variable strategy.

**Comment by jl-wynen** [comment] 2023-01-11 15:52
I can't reproduce the failure on my machine. The error message does not include enough information to reproduce the input. But I tried with three different masks:
```python
mask0 = sc.ones(sizes={'': 4, '2': 9, '0': 4}, dtype=bool)
mask1 = sc.array(dims=['', '2', '0'], values=np.random.randint(0, 2, (4, 9, 4)), dtype=bool)
mask2 = sc.zeros(sizes={'': 4, '2': 9, '0': 4}, dtype=bool)
```
`mask0` matches the failing test input as far as I can see it. And it does indeed make the test take the longest.
I don't know if there can be a pathological mask that causes the test to take much longer than `mask0`.

@YooSunYoung can you add `from hypothesis import note` outside of the test and at the beginning of the test `note(list(mask.values))`, see if you get a failure again, and post the output again?

**Comment by YooSunYoung** [comment] 2023-02-16 08:29
@jl-wynen I don't get the failure anymore. 
Should we close this...? Or did we want to test something more...? 
Sorry, I don't quite remember...

**Comment by jl-wynen** [comment] 2023-02-24 10:24
Let's close this for now since it does not affect any users. We can revisit it if the issue pops up again.

**Closed by jl-wynen** 2023-02-24 10:24 UTC
