### ISSUE TITLE
conda installation lacks dependencies

### ISSUE THREAD

**Issue by thomasholmrod** [scipp/scipp#556] opened 2019-09-18 14:21 UTC
when I install scipp v 1.0 on Ubuntu 18.04 LTS in a newly created environment, the conda installation fails because (in my case) three dependencies are not defined. I get the following message:
```
thomas@Skyridge:~$ conda create -n scipp -c scipp scipp
Fetching package metadata ...........
Solving package specifications: 

PackageNotFoundError: Dependencies missing in current linux-64 channels: 
  - scipp -> libgcc-ng >=7.3.0
  - scipp -> libstdcxx-ng >=7.3.0
  - scipp -> numpy 1.14.*
```

after having installed proper versions of the three packages I am able to install scipp. At this point my environment looks like this:

```# packages in environment at /home/thomas/anaconda3/envs/tofimg:
#
blas                      1.0                         mkl    anaconda
ca-certificates           2019.5.15                     1    anaconda
certifi                   2019.6.16                py37_1    anaconda
intel-openmp              2019.4                      243    anaconda
libedit                   3.1.20181209         hc058e9b_0    anaconda
libffi                    3.2.1                h4deb6c0_3    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py37he904b0f_0    anaconda
mkl_fft                   1.0.14           py37ha843d7b_0    anaconda
mkl_random                1.0.2            py37hd81dba3_0    anaconda
ncurses                   6.1                  he6710b0_1    anaconda
numpy                     1.14.6           py37h3b04361_4    anaconda
numpy-base                1.14.6           py37h81de0dd_4    anaconda
openssl                   1.1.1                h7b6447c_0    anaconda
pip                       19.2.2                   py37_0    anaconda
python                    3.7.4                h265db76_1    anaconda
readline                  7.0                  h7b6447c_5    anaconda
scipp                     v0.1                     py37_0    scipp
setuptools                41.0.1                   py37_0    anaconda
six                       1.12.0                   py37_0    anaconda
sqlite                    3.29.0               h7b6447c_0    anaconda
tk                        8.6.8                hbc83047_0    anaconda
wheel                     0.33.4                   py37_0    anaconda
xz                        5.2.4                h14c3975_4    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
```

btw, I note that the version of scipp is v0.1 rather than just 0.1, which is a bit unusual.

**Comment by SimonHeybrock** [comment] 2019-09-19 05:20
I cannot reproduce this (I am also running 18.04). conda resolves the dependencies correctly here and installs those packages. @DanNixon do you have an idea what could be going on?

> btw, I note that the version of scipp is v0.1 rather than just 0.1, which is a bit unusual.
Good point, I will fix that.

**Comment by SimonHeybrock** [comment] 2019-09-19 05:24
@thomasholmrod Could your conda config is missing the `defaults` channel? My `~/.condarc` looks as follows:

```
channels:
  - defaults
```

**Comment by SimonHeybrock** [comment] 2019-10-21 10:42
Closing since this does not appear to be a scipp issue.

**Closed by SimonHeybrock** 2019-10-21 10:42 UTC
